/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Person;
import javax.swing.JOptionPane;
import Model.Contact;

/**
 *
 * @author saketh
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    private Person person;
    
    public MainJframe() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        streetCurrent = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nuid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        collegeName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aptCurrent = new javax.swing.JTextField();
        cityCurrent = new javax.swing.JTextField();
        zipCurrent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        streetPermanent = new javax.swing.JTextField();
        aptPermanent = new javax.swing.JTextField();
        cityPermanent = new javax.swing.JTextField();
        zipPermanent = new javax.swing.JTextField();
        phoneCurrent = new javax.swing.JTextField();
        emailCurrent = new javax.swing.JTextField();
        phonePermanent = new javax.swing.JTextField();
        emailPermanent = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        viewApt = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewZip = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewStreetP = new javax.swing.JLabel();
        viewAptp = new javax.swing.JLabel();
        viewCityp = new javax.swing.JLabel();
        viewZipp = new javax.swing.JLabel();
        viewPhone = new javax.swing.JLabel();
        viewEmail = new javax.swing.JLabel();
        viewPhonep = new javax.swing.JLabel();
        viewEmailp = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setText("Street");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        Button.setText("Save");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 20));
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, 30));
        jPanel1.add(streetCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 120, 30));

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, 30));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        nuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuidActionPerformed(evt);
            }
        });
        jPanel1.add(nuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, 30));

        jLabel4.setText("NUID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        collegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeNameActionPerformed(evt);
            }
        });
        jPanel1.add(collegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, 30));

        jLabel5.setText("College Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));
        jPanel1.add(aptCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 30));
        jPanel1.add(cityCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 120, 30));
        jPanel1.add(zipCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 120, 30));

        jLabel6.setText("Apt No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel7.setText("City");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel8.setText("ZipCode");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel9.setText("Street");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel10.setText("Apt No.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel11.setText("City");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel12.setText("ZipCode");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        streetPermanent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetPermanentActionPerformed(evt);
            }
        });
        jPanel1.add(streetPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 130, 30));
        jPanel1.add(aptPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 130, 30));
        jPanel1.add(cityPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 130, 30));
        jPanel1.add(zipPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, 30));
        jPanel1.add(phoneCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 100, 30));
        jPanel1.add(emailCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 100, 30));
        jPanel1.add(phonePermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, 30));

        emailPermanent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPermanentActionPerformed(evt);
            }
        });
        jPanel1.add(emailPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, 30));

        jLabel13.setText("Phone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel14.setText("Email");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel15.setText("Phone");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel16.setText("Email");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("STUDENT DETAILS");
        jLabel17.setToolTipText("");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, 20));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CURRENT ADDRESS");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 200, 20));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("PERMANENT ADDRESS");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 230, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("PERSONAL CONTACT");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 20));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("OFFICE CONTACT");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 268, 170, -1));

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("HUSKY CARD FORM");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 460, 30));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewName.setText("First Name");
        jPanel2.add(viewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        viewStreet.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewStreet.setText("Street");
        jPanel2.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        viewNuid.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewNuid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewNuid.setText("NUID");
        jPanel2.add(viewNuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 130, 80, -1));

        viewApt.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewApt.setText("Apt No.");
        jPanel2.add(viewApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        viewCity.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewCity.setText("City");
        jPanel2.add(viewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        viewZip.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewZip.setText("ZipCode");
        jPanel2.add(viewZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        viewLastName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLastName.setText("Last Name");
        jPanel2.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 80, 20));

        viewCollegeName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewCollegeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewCollegeName.setText("College Name");
        jPanel2.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        viewStreetP.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewStreetP.setText("Street");
        jPanel2.add(viewStreetP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 130, -1));

        viewAptp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewAptp.setText("Apt No.");
        jPanel2.add(viewAptp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        viewCityp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewCityp.setText("City");
        jPanel2.add(viewCityp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        viewZipp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewZipp.setText("ZipCode");
        jPanel2.add(viewZipp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        viewPhone.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewPhone.setText("Phone");
        jPanel2.add(viewPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        viewEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewEmail.setText("Email");
        jPanel2.add(viewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        viewPhonep.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewPhonep.setText("Phone");
        jPanel2.add(viewPhonep, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        viewEmailp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewEmailp.setText("Email");
        jPanel2.add(viewEmailp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel23.setText("HUSKY CARD");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setText("STUDENT DETAILS");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel25.setText("FIRST NAME");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel26.setText("LAST NAME");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel27.setText("NUID");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel28.setText("COLLEGE NAME");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setText("CURRENT ADDRESS");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel30.setText("STREET");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel31.setText("APT NO.");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel32.setText("CITY");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel33.setText("ZIPCODE");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setText("PERMANENT ADDRESS");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel35.setText("STREET");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel36.setText("APT NO.");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel37.setText("CITY");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel38.setText("ZIPCODE");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setText("PERSONAL CONTACT");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setText("OFFICIAL CONTACT");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel41.setText("PHONE");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel42.setText("EMAIL");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel43.setText("PHONE");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel44.setText("EMAIL");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        
        String name = firstName.getText();
        String Nuid = nuid.getText();
        String Lastname = lastName.getText();
        String CollegeName = collegeName.getText();
        String peremail = emailPermanent.getText();
        String curemail= emailCurrent.getText();
        String curphone = phoneCurrent.getText();
        String perphone = phonePermanent.getText();
        String curStreet = streetCurrent.getText();
        String curApt = aptCurrent.getText();
        String curCity = cityCurrent.getText();
        String curZip = zipCurrent.getText();
        String perStreet = streetPermanent.getText();
        String perApt = aptPermanent.getText();
        String perCity = cityPermanent.getText();
        String perZip = zipPermanent.getText();
     
        this.person.setFirstName(name);
        this.person.setNuid(Nuid);
        this.person.setLastname(Lastname);
        this.person.setCollegename(CollegeName);
        
        Contact contact = this.person.getOfficeContact();
        contact.setEmail(peremail);
        Contact currentcontact = this.person.getPersonalContact();
        currentcontact.setEmail(curemail);
        Contact currentphone = this.person.getOfficeContact();
        currentphone.setPhone(curphone);
        Contact permanentphone = this.person.getPersonalContact();
        permanentphone.setPhone(perphone);
        
        Address currentstreet = this.person.getCurrentAddress();
        currentstreet.setStreetName(curStreet);
        Address currentapt = this.person.getCurrentAddress();
        currentapt.setAptNo(curApt);
        Address currentcity = this.person.getCurrentAddress();
        currentcity.setCity(curCity);
        Address currentzip = this.person.getCurrentAddress();
        currentzip.setZipCode(curZip);
        
        Address permanentstreet = this.person.getPermanentAddress();
        permanentstreet.setStreetName(perStreet);
        Address permanentapt = this.person.getPermanentAddress();
        permanentapt.setAptNo(perApt);
        Address permanentcity = this.person.getPermanentAddress();
        permanentcity.setCity(perCity);
        Address permanentzip = this.person.getPermanentAddress();
        permanentzip.setZipCode(perZip);
        
        
        JOptionPane.showMessageDialog(null, "Saved Succesfully");
        
        display();
    }//GEN-LAST:event_ButtonActionPerformed

    private void nuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuidActionPerformed

    private void collegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeNameActionPerformed

    private void emailPermanentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPermanentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPermanentActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void streetPermanentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetPermanentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetPermanentActionPerformed

    private void display(){
        
        Person obj2 = new Person();
        viewName.setText(this.person.getFirstName());
        viewNuid.setText(this.person.getNuid());
        viewLastName.setText(this.person.getLastname());
        viewCollegeName.setText(this.person.getCollegename());
        viewEmailp.setText(this.person.getOfficeContact().getEmail());
        viewEmail.setText(this.person.getPersonalContact().getEmail());
        viewPhone.setText(this.person.getOfficeContact().getPhone());
        viewPhonep.setText(this.person.getPersonalContact().getPhone());
        viewStreet.setText(this.person.getCurrentAddress().getStreetName());
        viewApt.setText(this.person.getCurrentAddress().getAptNo());
        viewCity.setText(this.person.getCurrentAddress().getCity());
        viewZip.setText(this.person.getCurrentAddress().getZipCode());
        viewStreetP.setText(this.person.getPermanentAddress().getStreetName());
        viewAptp.setText(this.person.getPermanentAddress().getAptNo());
        viewCityp.setText(this.person.getPermanentAddress().getCity());
        viewZipp.setText(this.person.getPermanentAddress().getZipCode());
    }
        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JTextField aptCurrent;
    private javax.swing.JTextField aptPermanent;
    private javax.swing.JTextField cityCurrent;
    private javax.swing.JTextField cityPermanent;
    private javax.swing.JTextField collegeName;
    private javax.swing.JTextField emailCurrent;
    private javax.swing.JTextField emailPermanent;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField nuid;
    private javax.swing.JTextField phoneCurrent;
    private javax.swing.JTextField phonePermanent;
    private javax.swing.JTextField streetCurrent;
    private javax.swing.JTextField streetPermanent;
    private javax.swing.JLabel viewApt;
    private javax.swing.JLabel viewAptp;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCityp;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewEmail;
    private javax.swing.JLabel viewEmailp;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewPhone;
    private javax.swing.JLabel viewPhonep;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewStreetP;
    private javax.swing.JLabel viewZip;
    private javax.swing.JLabel viewZipp;
    private javax.swing.JTextField zipCurrent;
    private javax.swing.JTextField zipPermanent;
    // End of variables declaration//GEN-END:variables
}
