/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author saketh
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form MedicineAssignJPanel
     */
    

    MedicineAssignJPanel(Application application) {
        initComponents();
        
        this.application = application;
        
        populateDropdowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineBox = new javax.swing.JComboBox();
        assignMedBtn = new javax.swing.JButton();
        observationBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 38, 116, 48));

        assignMedBtn.setText("Assign");
        assignMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedBtnActionPerformed(evt);
            }
        });
        add(assignMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 177, -1, -1));

        observationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                observationBoxItemStateChanged(evt);
            }
        });
        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 38, 133, 48));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 133, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedBtnActionPerformed
        // TODO add your handling code here:
        
        Observation o = (Observation) observationBox.getSelectedItem();
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        
        o.setMedication(m);
    }//GEN-LAST:event_assignMedBtnActionPerformed

    private void observationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_observationBoxItemStateChanged
        // TODO add your handling code here:
        
        Observation o = (Observation) observationBox.getSelectedItem();
        
        if(o.getMedication() != null){
            jLabel1.setText(o.getMedication().getMedicineName());
        }
        
    }//GEN-LAST:event_observationBoxItemStateChanged
    public void populateDropdowns(){
      ArrayList<Medicine>  medicines = this.application.getCatalog().getMedicineList();
      
      ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
      
      for(Observation o: observations){
          observationBox.addItem(o);
      }
      for (Medicine med: medicines) {
          medicineBox.addItem(med);
      }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    // End of variables declaration//GEN-END:variables
}
